(function ($) {
  $.fn.datepicker.language["en"] = {
    days: [
      "Chủ nhật",
      "Thứ 2",
      "Thứ 3",
      "Thứ 4",
      "Thứ 5",
      "Thứ 6",
      "Thứ 7",
    ],
    daysShort: ["cn", "2", "3", "4", "5", "6", "7"],
    daysMin: ["cn", "2", "3", "4", "5", "6", "7"],
    months: [
      "Tháng 1",
      "Tháng 2",
      "Tháng 3",
      "Tháng 4",
      "Tháng 5",
      "Tháng 6",
      "Tháng 7",
      "Tháng 8",
      "Tháng 9",
      "Tháng 10",
      "Tháng 11",
      "Tháng 12",
    ],
    monthsShort: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
    ],
    today: "Hôm nay",
    clear: "xóa",
    dateFormat: "dd/mm/yyyy",
    timeFormat: "hh:ii aa",
    firstDay: 0,
  };
})(jQuery);
